[package]
name = "cookie-monster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies,request]
version = "0.11.12"
features = ["cookies"]

[dependencies.cookie]
version = "0.16"
features = ["secure"]